### ISSUE TITLE
Gaem lacks a license

### ISSUE THREAD

**Issue by nabijaczleweli** [Skorezore/Gaem#10]
Shall we go for the one and only MIT license?

**Comment by nmai** [comment]
Sounds good but it the license should require that people include the line "All Hail Lord Nooble" at the end of their credits.

**Comment by nabijaczleweli** [comment]
It requires LICENSE in root and a header in every file
@Skorezore pls confirm use of MIT license

**Comment by skorezore** [comment]
Yes let's go ahead and use the MIT license.

**Comment by nabijaczleweli** [comment]
Good, push incoming

**Comment by rmartinho** [comment]
CC0 best license.

**Comment by skorezore** [comment]
<s>Hi Robot.</s> ALL YOUR BASE ARE BELONG TO US <--- My comment got hijacked.
