### ISSUE TITLE
Gaem doesn't have options

### ISSUE THREAD

**Issue by nabijaczleweli** [Skorezore/Gaem#12]
We need to add options (a.k.a. config) or TotalBiscuit will yell at us.
I propose use of my buttiful library, [Cpponfiguration](https://github.com/nabijaczleweli/Cpponfiguration)

I still don't know what to configure in our glorious Gaem, but hey

**Comment by nabijaczleweli** [comment]
Actually I have an idea: main menu and config screen and whatnot
As for things to configure: framerate

**Comment by skorezore** [comment]
Yes we can configure the refresh rate, but we're then going to have to implement delta time.
