### ISSUE TITLE
Characters being overwritten if moving sideways mid air.

### ISSUE THREAD

**Issue by skorezore** [Skorezore/Gaem#13]
![screenshot](https://cloud.githubusercontent.com/assets/8404756/8858728/0a00f97e-3147-11e5-9b92-e6831ef21f1a.png)

This should be an easy fix. The problem is that collision detection isn't working for +2 character movement.

**Comment by nabijaczleweli** [comment]
Next time plz use "Closes #N" notation

**Comment by skorezore** [comment]
Okayz.

**Comment by nabijaczleweli** [comment]
Still sometimes overrides when moving sideways...

**Comment by nmai** [comment]
Is it important that characters collide with each other?

**Comment by nabijaczleweli** [comment]
Huh?

**Comment by nmai** [comment]
I don't think that's what this issue is about but I was referring to this quote: "This should be an easy fix. The problem is that collision detection isn't working for +2 character movement."

Perhaps I misinterpreted it?

**Comment by nabijaczleweli** [comment]
Player should never be able to move to a cell, that is not `game_screen::filler`, if that's what you're asking
