### ISSUE TITLE
We need non-windows builds

### ISSUE THREAD

**Issue by nabijaczleweli** [Skorezore/Gaem#15]
How about [Travis](https://travis-ci.org)? I can do a nice setup there.

**Comment by nabijaczleweli** [comment]
@Skorezore opinion plz

**Comment by skorezore** [comment]
Yes go ahead.

**Comment by nabijaczleweli** [comment]
Closed by #17
Builds available [here](https://travis-ci.org/Skorezore/Gaem)
Binaries auto-uploaded [here](https://www.dropbox.com/sh/3v8wry9vsocgcrc/AADseRZlthoGgK4ZXdvjgfvQa?dl=0)
