### ISSUE TITLE
Able to escape map

### ISSUE THREAD

**Issue by ChemiCalChems** [Skorezore/Gaem#27]
Only 19 columns print onto my terminal window. 
![screenshot from 2015-07-27 00 50 13](https://cloud.githubusercontent.com/assets/9658223/8896390/b7521b52-33fa-11e5-81f6-6d0d37bbf357.png)
I can actually go outside the screen and float forever, but when I push down a couple of times, I die. 
![screenshot from 2015-07-27 00 52 01](https://cloud.githubusercontent.com/assets/9658223/8896394/cb591c2c-33fa-11e5-95aa-37bd52afa387.png)
OS: Ubuntu 14.04.2 LTS
Kernel: 3.16.0-43-generic

Steps to reproduce:
1. Clone from repo. 
2. `make CXX=g++-5` and run `binaries/gaem`. 
3. Start the game, and it's broken. 

**EDIT**: Tried using the precompiled version. Same exact errors.

May be a flaw in my system, but I really don't think it is.

**Comment by nabijaczleweli** [comment]
Post your savefile

**Comment by ChemiCalChems** [comment]
@nabijaczleweli  Not to be found.

**Comment by nabijaczleweli** [comment]
What does

> Map not loading completely

mean, then?

**Comment by ChemiCalChems** [comment]
@nabijaczleweli  Exactly what the screenshots show. Only 19 columns are printed. Are more to be expected or not?

**Comment by nabijaczleweli** [comment]
The default map size is 15 by 15, did you increase it?
You should not be able to move out of the map

**Comment by ChemiCalChems** [comment]
@nabijaczleweli As the second screenshot shows, I can even die outside. Didn't change anything in the source code.

**Comment by nabijaczleweli** [comment]
How did you escape the map?
Repeated pressing of "D"?

**Comment by nmai** [comment]
@nabijaczleweli Are you building/testing primarily on Linux or Windows?

**Comment by ChemiCalChems** [comment]
@nabijaczleweli  Combination of D and W. @nmai Ubuntu, stated in the ticket.

**Comment by nmai** [comment]
@ChemiCalChems Oh man you weren't kidding about your name being difficult to pronounce haha

**Comment by ChemiCalChems** [comment]
@nmai It's quite straight forward actually. That's another spelling. But the pronunciation is exactly the same as [this](https://translate.google.com/#en/es/chema). Just hit the speak button.

**Comment by nabijaczleweli** [comment]
Could you post the key combo that lets you leave?

**Comment by ChemiCalChems** [comment]
@nabijaczleweli I'll record footage.

**Comment by ChemiCalChems** [comment]
@nabijaczleweli [Footage](https://www.youtube.com/watch?v=2fszORhzpVM) As you can see, first time I got a float exception, then I exited the screen, and also broke the gravity by pushing S a couple of times. I died offscreen too.

**Comment by nabijaczleweli** [comment]
@ChemiCalChems You're running an old-ass version, get yerself 58 from dropbox or clone from master

**Comment by nabijaczleweli** [comment]
Experiencing that as well now, though the issue name didn't make sense

**Comment by nabijaczleweli** [comment]
Closed via https://github.com/Skorezore/Gaem/commit/cdfb8fc88db87a3bc042521d7e36a7606a29d548
