### ISSUE TITLE
There should be as many spikes as the gaem_screen is wide

### ISSUE THREAD

**Issue by nabijaczleweli** [Skorezore/Gaem#28]
Simple fix: replace `"^^^^^^^^^^^^^^^"` with `string('^', screen.size.x)` or `string('^', screen.size.x - 1)`

**Comment by nmai** [comment]
Does the Gaem view scale with the parent window? if so, should there be a limit?

**Comment by nabijaczleweli** [comment]
It doesn't _scale_, but there should be a limit
