### ISSUE TITLE
Gaem should be cross-platform.

### ISSUE THREAD

**Issue by skorezore** [Skorezore/Gaem#6]
Currently, it only works for Windows systems. To fix this, `getch()` & `kbhit()`should be implemented for Linux. Likewise, the `system()` calls need to be changed to call `clear` instead of `cls` in the Linux implementation.

**Comment by nabijaczleweli** [comment]
[About that...](http://homepage.ntlworld.com./jonathan.deboynepollard/FGA/clearing-the-tui-screen.html)

**Comment by skorezore** [comment]
Well we can't really scroll to a blank console unless we know how many lines there are, and this isn't fixed--most consoles are resizable.

**Comment by skorezore** [comment]
And since there is no cross-platform way to get/set the number of lines in a console window, 'system', although generally considered bad practice, is our best option.

**Comment by nabijaczleweli** [comment]
Or we could get a very minimal curses setup (until we get into ANSIGL (see #7)) and just do

``` c
#include <curses.h>
// ...
wclear(window);
wrefresh(window);
```

I remember that `window` being obtainable from somewhere global, but too late for doc searching

**Comment by skorezore** [comment]
Ahh yes. This seems like the ideal solution.

**Comment by nabijaczleweli** [comment]
Finishing up curses support...

**Comment by nabijaczleweli** [comment]
Closed via https://github.com/Skorezore/Gaem/commit/1548580912890c6de21aa3bd03f4376c42cbb3f2
