### ISSUE TITLE
Gaem needs to support ANSI color codes

### ISSUE THREAD

**Issue by nmai** [Skorezore/Gaem#7]
Gaem should render in full color on all superior systems that support ANSI color code (i.e. Linux, OS X).

**Comment by nabijaczleweli** [comment]
Unfortunately Windows' `cmd` doesn't support ANSI color codes, only WinAPI calls how could that be resolved?
Should we use a library for colours?

**Comment by CinchBlue** [comment]
Switch to a curses library or use Cygwin.

**Comment by nabijaczleweli** [comment]
If we're going curses, we should go all out and use AnsiGL [(which also recently migrated to HitHub)](https://github.com/nicrohobak/AnsiGL), IMO

**Comment by nmai** [comment]
+1, I highly endorse this decision

**Comment by nabijaczleweli** [comment]
As for now we might want to use [this](https://github.com/joakimkarlsson/bandit/blob/master/bandit/reporters/colorizer.h). Capturing the colorized output would be non-trivial on Windows, but I could make it work

**Comment by skorezore** [comment]
AnsiGL seems nice.

**Comment by skorezore** [comment]
<s>Yes I'm going to go ahead and try to implement AnsiGL. Making branch [`ansigl-port`](https://github.com/Skorezore/Gaem/tree/ansigl-port) for that.</s>
AnsiGL abbadoned as per http://chat.stackoverflow.com/transcript/message/24635502#24635502
-- @nabijaczleweli
