### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by skorezore** [Skorezore/Gaem#8]
Compilation now fails with the following error:

`class std::vector<coords>' has no member named 'emplace_front`

**Comment by nabijaczleweli** [comment]
Should we use `std::forward_list`, `std::deque` or `std::list` for `Player::prev_positions`?

**Comment by nabijaczleweli** [comment]
Whoops, `std::forward_list` is a bad idea

**Comment by skorezore** [comment]
I see you've closed the issue, but I would've said to use `std::list`.

**Comment by nabijaczleweli** [comment]
> Thou shalt obey the holy words of the mighty Jerry Coffin.

Ogreed, that `std::list` would be somewhat better, bit I think `std::forward_list` is _just_ what we need.
Leaving the final decision to you, though
