### ISSUE TITLE
Gravity doesn't exist just below the platforms

### ISSUE THREAD

**Issue by nabijaczleweli** [Skorezore/Gaem#9]
@Skorezore, since you're the original author please confirm, that this is the expected behaviour

**Comment by nmai** [comment]
Well clearly the solution is to re-work the game physics and implement interpolated collision detection + quadtrees.

**Comment by nabijaczleweli** [comment]
Are you @Skorezore? Please let @Skorezore speak about that.

**Comment by skorezore** [comment]
Gravity should exist below the platforms.

**Comment by skorezore** [comment]
In fact, I think it does. Have you never died below a platform @nabijaczleweli?

**Comment by nabijaczleweli** [comment]
The "pixel" one below the platform, as in:

```

=====
    X ==

```

and I can stay there forever. This'll be a quick fix
